language: node_js
node_js:
- '0.10'
- '0.12'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install && npm install bower
- bower install
script:
  - npm run test:coverage
after_success:
  - npm run test:report